all:
  children:

    nas:
      hosts:
        truenas:
          ansible_host: 192.168.0.180
          ansible_user: root

    cluster:
      children:

        x86_servers:
          hosts:
            node01:
              ansible_host: 192.168.0.104
            node02:
              ansible_host: 192.168.0.105

        pi_nodes:
          hosts:
            pi-node01:
              ansible_host: 192.168.0.201
            pi-node02:
              ansible_host: 192.168.0.202
            pi-node03:
              ansible_host: 192.168.0.203
            pi-node04:
              ansible_host: 192.168.0.204

  vars:
    ansible_user: venom
