all:
  children:

    nas:
      hosts:
        truenas:
          ansible_host: 192.168.0.180
          ansible_user: root

    cluster:
      children:

        x86_servers:
          hosts:
            node01:
              ansible_host: 192.168.0.104
            node02:
              ansible_host: 192.168.0.105

        pi_nodes:
          hosts:
            pi-node01:
              ansible_host: 192.168.0.201
            pi-node02:
              ansible_host: 192.168.0.202
            pi-node03:
              ansible_host: 192.168.0.203
            pi-node04:
              ansible_host: 192.168.0.204

    # k3s-ansible expects these group names
    k3s_cluster:
      children:
        server:
          hosts:
            node01:    # first server — bootstraps etcd (cluster-init)
            node02:    # second server
            pi-node02: # third server (etcd member)
        agent:
          hosts:
            pi-node01:
            pi-node03:
            pi-node04:

  vars:
    ansible_user: venom
    ansible_python_interpreter: /usr/bin/python3
